/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_commonsware_cwac_anddown_AndDown */

#ifndef _Included_com_commonsware_cwac_anddown_AndDown
#define _Included_com_commonsware_cwac_anddown_AndDown
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_commonsware_cwac_anddown_AndDown
 * Method:    markdown
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_commonsware_cwac_anddown_AndDown_markdown
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
