name: "Feature request"
description: "Submit a feature or enhancement request and help to improve the project"
body:
  - type: markdown
    attributes:
      value: |
        ### ðŸ‘ Thank you for contributing to the project!
        Please note this is a **free and open-source** project. People take their own **free time** to help you, so please, be patient.
  - type: checkboxes
    id: before-posting
    attributes:
      label: "âš ï¸ This issue respects the following points: âš ï¸"
      description: All conditions are **required**. Your issue can be closed if these are checked incorrectly.
      options:
        - label: This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
          required: true
        - label: The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
          required: true
        - label: Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub. 
          required: true
        - label: The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)
          required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description:  What do you want (or not want) and where do you want it?
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: Information
      description: What is your Android version? What device? (In case of custom ROM, what ROM?)
      value: |
        Android version: 
        Device: 
        App Version: 
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Source
      description: Where did you get & install the application from?
      options: ["F-Droid", "GitHub Releases", "git master branch", "Google Play", "Aptoide", "Something else (-> Additional info)"]
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: Format / File type
      description: Is the request about a specific format (i.e. Markdown/todo.txt)?
      options: ["Not specific", "Markdown", "todo.txt", "Wikitext, Zim", "Key-Value (json/yaml/ini..)", "Plaintext", "Binary", "Something else (-> Additional info)"]
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Additional info / Log
      description: Leave any additional information or logs here.
      render: shell
      value: "-"
